In [1]:
import pandas as pd
import numpy as np

In [2]:
dt = pd.read_csv("IRIS.csv")
dt.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
dt.shape

(150, 5)

In [4]:
dt.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [5]:
#converting categorical value into numerical value
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()

dt['species']=l.fit_transform(dt['species'])

dt

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [6]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

X = dt.values[:,1:4]
Y = dt.values[:,4]
Y=Y.astype('int')

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3) # 70% training and 30% test

In [7]:
X_train.shape

(105, 3)

In [8]:
y_train.shape

(105,)

In [9]:
X_test

array([[2.7, 3.9, 1.2],
       [3.1, 4.9, 1.5],
       [3. , 6.1, 2.3],
       [3.3, 1.7, 0.5],
       [3.8, 1.9, 0.4],
       [2. , 3.5, 1. ],
       [2.8, 5.1, 1.5],
       [2.8, 4. , 1.3],
       [2.3, 4.4, 1.3],
       [3.8, 1.7, 0.3],
       [3.7, 1.5, 0.2],
       [2.8, 6.1, 1.9],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [2.8, 5.1, 2.4],
       [2.4, 3.3, 1. ],
       [3.3, 5.7, 2.1],
       [3. , 4.4, 1.4],
       [3.5, 1.4, 0.3],
       [2.8, 4.7, 1.2],
       [2.8, 4.8, 1.4],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3. , 1.3, 0.2],
       [3.3, 4.7, 1.6],
       [3. , 5.2, 2.3],
       [3.1, 5.6, 2.4],
       [3. , 5.5, 2.1],
       [2.2, 5. , 1.5],
       [3. , 5.9, 2.1],
       [3.2, 1.3, 0.2],
       [2.8, 4.6, 1.5],
       [3. , 5.2, 2. ],
       [3. , 4.2, 1.5],
       [2.7, 5.3, 1.9],
       [3.6, 6.1, 2.5],
       [3.1, 1.5, 0.1],
       [3. , 1.4, 0.2],
       [2.6, 4. , 1.2],
       [3.9, 1.3, 0.4],
       [4.1, 1.5, 0.1],
       [3.4, 5.6

In [10]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

for k in range(25) :
    #Create KNN Classifier
    kv = k+1
    knn = KNeighborsClassifier(n_neighbors=kv)

    #Train the model using the training sets
    knn.fit(X_train, y_train)

    from sklearn.metrics import accuracy_score
    print("k = " , kv , "accuracy score = " , accuracy_score(y_test,knn.predict(X_test)))

k =  1 accuracy score =  0.9555555555555556
k =  2 accuracy score =  0.9555555555555556
k =  3 accuracy score =  0.9555555555555556
k =  4 accuracy score =  0.9555555555555556
k =  5 accuracy score =  0.9555555555555556
k =  6 accuracy score =  0.9555555555555556
k =  7 accuracy score =  1.0
k =  8 accuracy score =  1.0
k =  9 accuracy score =  1.0
k =  10 accuracy score =  1.0
k =  11 accuracy score =  1.0
k =  12 accuracy score =  1.0
k =  13 accuracy score =  1.0
k =  14 accuracy score =  1.0
k =  15 accuracy score =  1.0
k =  16 accuracy score =  1.0
k =  17 accuracy score =  1.0
k =  18 accuracy score =  1.0
k =  19 accuracy score =  1.0
k =  20 accuracy score =  1.0
k =  21 accuracy score =  1.0
k =  22 accuracy score =  1.0
k =  23 accuracy score =  1.0
k =  24 accuracy score =  1.0
k =  25 accuracy score =  1.0


In [11]:
y_pred = knn.predict(X_test)
y_pred

array([1, 1, 2, 0, 0, 1, 2, 1, 1, 0, 0, 2, 0, 0, 2, 1, 2, 1, 0, 1, 1, 0,
       0, 0, 1, 2, 2, 2, 2, 2, 0, 1, 2, 1, 2, 2, 0, 0, 1, 0, 0, 2, 2, 1,
       0])

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [13]:
# Create a Random Forest Classifier model (effective for Iris dataset)
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the testing set
predictions = model.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy:.4f}")



Accuracy: 0.9556


In [14]:
from sklearn import metrics
metrics.confusion_matrix(y_test,y_pred)

array([[16,  0,  0],
       [ 0, 14,  0],
       [ 0,  0, 15]], dtype=int64)

In [15]:
metrics.precision_score(y_test,y_pred,average='micro')

1.0

In [16]:
from sklearn import tree

In [17]:
# build model with DecisionTreeClassifier
model1=tree.DecisionTreeClassifier()

In [18]:
# fitting x as independent variables and y as dependent variable
model1.fit(X_train,y_train)

DecisionTreeClassifier()

In [19]:
y_pred=model1.predict(X_test)
print(y_test)
print(y_pred)

[1 1 2 0 0 1 2 1 1 0 0 2 0 0 2 1 2 1 0 1 1 0 0 0 1 2 2 2 2 2 0 1 2 1 2 2 0
 0 1 0 0 2 2 1 0]
[1 1 2 0 0 1 1 1 1 0 0 2 0 0 2 1 2 1 0 1 1 0 0 0 1 2 2 2 1 2 0 1 2 1 2 2 0
 0 1 0 0 2 2 1 0]


In [20]:
model1.score(X_test,y_test)

0.9555555555555556

In [23]:
n=[[3.0,5.1,1.8]]
prd = model.predict(n)
prd

array([2])